version: '3.8'
services:
  nginx: 
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"
    # volumes:
    #   - ./config/nginx.conf:/etc/nginx/nginx.conf
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager