version: '3.8'
services:
  nginx: 
    image: mycujoo/nginx-http-flv-module
    ports:
      - "1965:1965"
      - "8181:8181"
    volumes:
      - ./config/nginx.conf:/opt/nginx/nginx.conf:rw
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager